### ISSUE TITLE
Browse tasks - I see only a limited number of tasks

### ISSUE THREAD

**Issue by rosymond** [CitizenScienceCenter/c3s-lab-client#38] opened 2021-02-10 10:22 UTC
I just created a test project "Test Ana" to analyse tweets.
I imported 20 tweets at creation.
However, if I look at "Browse tasks" (in the dashboard) I only see 10 tasks.
If I "export tasks" I see in the downloaded file that, indeed, there are 20 tasks in the project.

Maybe a problem with pagination?

**Comment by andres112** [comment] 2021-02-10 14:26
After a detailed revision, was possible to see that the problem is caused by the attribute **n_tastks** contained in the response from the server when a getProjectTasks request is triggered. So far, the issue was only checked when the project is in draft mode, is required to check if the issue exists when the project will be in published mode too.  Although all the tasks are included in the project, the parameter **n_tastks** is set to 0. @janCstoffregen

![image](https://user-images.githubusercontent.com/32916294/107522362-ed54ae80-6bb3-11eb-81d8-ebd88c889323.png)
![image](https://user-images.githubusercontent.com/32916294/107522385-f34a8f80-6bb3-11eb-864a-0150367492c4.png)

**Comment by janCstoffregen** [comment] 2021-03-02 21:14
... related to https://github.com/Scifabric/pybossa/issues/1907

**Comment by janCstoffregen** [comment] 2021-03-02 21:32
https://docs.pybossa.com/installation/guide/#running-asynchronous-tasks-in-the-background

**Comment by janCstoffregen** [comment] 2021-03-08 22:32
fixed here https://github.com/Crowd4SDG/pybossa-dev/issues/9, the bug is gone with the new deployment.

**Closed by janCstoffregen** 2021-03-08 22:32 UTC
Labels: bug
